### ISSUE TITLE
Use fetch_x5 func in ReatilHero notebook

### ISSUE THREAD

**Issue by maks-sh** [maks-sh/scikit-uplift#101]
## 💡 Feature request

The dataset is downloaded from the link in the RetailHero tutorials [EN](https://github.com/maks-sh/scikit-uplift/blob/master/notebooks/RetailHero_EN.ipynb) and [RU](https://github.com/maks-sh/scikit-uplift/blob/master/notebooks/RetailHero.ipynb). It is inconvenient and looks ugly:

![image](https://user-images.githubusercontent.com/17473095/124365888-caef2a80-dc53-11eb-89f5-8a42ae11d63b.png)

We have the [fetch_x5](https://www.uplift-modeling.com/en/latest/api/datasets/fetch_x5.html) function, which easily allows you to download the dataset.

It is necessary to rewrite these notebooks using the `fetch_x5` function.

**Comment by Ksyula** [comment]
I'll take it
