### ISSUE TITLE
EDA notebook for the X5 dataset

### ISSUE THREAD

**Issue by ElisovaIra** [maks-sh/scikit-uplift#103]
## 💡 Feature request

There are 4 datasets available for downloading in the `datasets` module.

It will be great to make EDA notebook on top of the [x5 dataset](https://www.uplift-modeling.com/en/latest/api/datasets/fetch_x5.html)  in `notebooks`. [fetch_x5](https://github.com/maks-sh/scikit-uplift/blob/e9de7abbb327fd461c1fe8bea5c4a1f25d0a823e/sklift/datasets/datasets.py#L171) function source code.

Points to include:

- how to download
- simple dataset EDA (include treatment column value_counts, target column value_counts) 
- simple model fit/predict

## Additional context

[Notebook example](https://github.com/maks-sh/scikit-uplift/blob/master/notebooks/uplift_metrics_tutorial.ipynb)

**Comment by patpanda94** [comment]
I would like to take this :)

**Comment by patpanda94** [comment]
PR #130
