### ISSUE TITLE
Bug when importing all metrics

### ISSUE THREAD

**Issue by ezhdi** [maks-sh/scikit-uplift#119]
## To Reproduce

`from sklift.metrics import *`

```
TypeError                                 Traceback (most recent call last)
<ipython-input-2-89f0d9d4fc6d> in <module>
----> 1 from sklift.metrics import *

~/anaconda3/lib/python3.7/importlib/_bootstrap.py in _handle_fromlist(module, fromlist, import_, recursive)

~/anaconda3/lib/python3.7/importlib/_bootstrap.py in _handle_fromlist(module, fromlist, import_, recursive)

TypeError: Item in sklift.metrics.__all__ must be str, not function
```

![Снимок экрана от 2021-07-18 14-49-27](https://user-images.githubusercontent.com/38072625/126064595-a761a5de-5424-48ff-8242-a9d2cc400ed7.png)

## Environment

 - scikit-uplift version (e.g., 0.1.2): 0.3.2
 - Python version (e.g., 3.7): 3.6

**Comment by maks-sh** [comment]
@ezhdi Thanks for reporting the bug.

Please make a submission on the ods.ai with a link to this issue.

I think you can easily fix this bug 👍

**Comment by ezhdi** [comment]
Take it
