### ISSUE TITLE
Add citation in the docstring

### ISSUE THREAD

**Issue by ElisovaIra** [maks-sh/scikit-uplift#126]
## 💡 Feature request

Add citation of the bibtex in the function docstring. 

Where: `fetch_criteo` function in the `datasets` module
[Code link ](https://github.com/maks-sh/scikit-uplift/blob/53ef4ef4b8dff64fce0bcb62f7e49dfa069d3dea/sklift/datasets/datasets.py#L257)

Type of docstring format: `Sphinx`

## Motivation

Please refer to the Criteo uplift dataset [page](https://ailab.criteo.com/criteo-uplift-prediction-dataset/):

![image](https://user-images.githubusercontent.com/16885007/126389041-5317c9fd-f78e-4423-a86c-a00df3f2b1c4.png)

## Additional context

Citation have to display in the correct format in the documentation files. 

Please provide screenshots.  

Documentation how to make citation in the Sphinx docstring
https://readthedocs.org/projects/sphinxcontrib-bibtex/downloads/pdf/latest/

### How to build documentation files

you can build the documentation locally using Sphinx 1.4 or later:

```
cd docs
pip install -r requirements.txt
make html
```
If you now point your browser to _build/html/index.html, you should see a documentation site.

(Navigate to doc file and right click -> open with `your_browser`)

**Comment by Ksyula** [comment]
take it

**Comment by Ksyula** [comment]
<img width="872" alt="Screenshot 2021-07-25 at 13 08 28" src="https://user-images.githubusercontent.com/25014494/126896949-b4b598d8-7db0-42ee-9955-792b00f24606.png">

**Comment by maks-sh** [comment]
@Ksyula What do you think to design all references in this style?

**Comment by Ksyula** [comment]
@maks-sh, sure, will do that

**Comment by Ksyula** [comment]
It seems that such changes will lead to restructuring docs. All references across the project's docs will be summarised in one place. The proper structure of the references either per docs module or for entire project should be defined first.
