### ISSUE TITLE
Add example of usages for fetch func

### ISSUE THREAD

**Issue by maks-sh** [maks-sh/scikit-uplift#127]
## 📚 Documentation

It is necessary to add examples with code for using these functions to the docstrings:
* `fetch_lenta`
* `fetch_x5`
* `fetch_criteo`
* `fetch_hillstrom`

An example of how to do this can be found [here](https://github.com/maks-sh/scikit-uplift/blob/master/sklift/models/models.py#L36).

It would also be nice to add a section `See also:`, which lists links to other datasets by analogy with [metrics](https://github.com/maks-sh/scikit-uplift/blob/master/sklift/metrics/metrics.py#L23).

**Comment by ezhdi** [comment]
I'll take
