### ISSUE TITLE
Check_consistent_length not found (plot_uplift_by_percentile)

### ISSUE THREAD

**Issue by tinder-davidkawashima** [maks-sh/scikit-uplift#13]
`NameError: name 'check_consistent_length' is not defined
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<command-64586> in <module>
----> 1 eval_obja = evaluate_uplift(models, datasets, feature_group, features_to_add[i], model_type)

<command-64550> in evaluate_uplift(lrModels, datasets, feature_list, features_to_add, model_type)
     69       #break
     70       print (key + " Curves")
---> 71       plot_uplift_by_percentile(y_true=dataset_uplift_eval["label"], uplift=dataset_uplift_eval["uplift_score"], treatment=dataset_uplift_eval["treatment"], strategy='overall', bins=100)
     72       plot_uplift_qini_curves(y_true=dataset_uplift_eval["label"], uplift=dataset_uplift_eval["uplift_score"], treatment=dataset_uplift_eval["treatment"], perfect=True)
     73       print ("Finished plotting curves")

/databricks/python/lib/python3.7/site-packages/sklift/viz/base.py in plot_uplift_by_percentile(y_true, uplift, treatment, strategy, bins)
    129 
    130     n_samples = len(y_true)
--> 131     check_consistent_length(y_true, uplift, treatment)
    132 
    133     if strategy not in strategy_methods:

NameError: name 'check_consistent_length' is not defined`

**Comment by ElisovaIra** [comment]
@tinder-davidkawashima Thank you for mention this issue. We are already working on it and it will be fixed in 0.1.2 release pretty soon.

**Comment by maks-sh** [comment]
Thanks for your bug report!

The new version 0.1.2 that fixes the bug is available in [pypi](https://pypi.org/project/scikit-uplift/0.1.2/) now.

**Comment by tinder-davidkawashima** [comment]
Awesome, works now! Thank you
