### ISSUE TITLE
RetailHero Dataset missing

### ISSUE THREAD

**Issue by set92** [maks-sh/scikit-uplift#143]
## 🐛 Bug

The URL that appears in the notebook is not working 

## To Reproduce

1. Open https://nbviewer.jupyter.org/github/maks-sh/scikit-uplift/blob/master/notebooks/RetailHero_EN.ipynb
2. Try to access the URL https://drive.google.com/u/0/uc?id=1fkxNmihuS15kk0PP0QcphL_Z3_z8LLeb&export=download
3. Error 404

**Comment by maks-sh** [comment]
Hi! 👋

Thank you a lot for the bug report 👍 It is very important for us.

Try to use the `fetch_x5` function: https://www.uplift-modeling.com/en/latest/api/datasets/fetch_x5.html

We have already updated this notebook [in the dev branch](https://github.com/maks-sh/scikit-uplift/blob/dev/notebooks/RetailHero_EN.ipynb). So, these changes will also appear in the master in the near future.

**Comment by maks-sh** [comment]
Fixed: https://nbviewer.jupyter.org/github/maks-sh/scikit-uplift/blob/master/notebooks/RetailHero_EN.ipynb
