### ISSUE TITLE
"About the company" section in each dataset

### ISSUE THREAD

**Issue by maks-sh** [maks-sh/scikit-uplift#155]
## 📚 Documentation

We really appreciate companies that share data with the community for building uplift models.
Therefore, we want to have a section **About the company** on the page of each dataset.

In this section, we would like to see the company's logo, a link, information about its activities, and much more.

![image](https://user-images.githubusercontent.com/17473095/129632710-72d0541d-0f5b-4ad9-8e8c-4f89c8ac89a3.png)

**Comment by Ksyula** [comment]
https://github.com/maks-sh/scikit-uplift/pull/161

**Comment by maks-sh** [comment]
Implemented in 0.4.1
