### ISSUE TITLE
Advanced uplift metrics tutorial notebook

### ISSUE THREAD

**Issue by ElisovaIra** [maks-sh/scikit-uplift#163]
### Create `uplift_metrics_tutorial_advanced.ipynb`

As a baseline take `uplift_metrics_tutorial.ipynb`

Use the same dataset. 

The next few points should be displayed:

1) `uplift@k` with a small step ot the k parameter (smaller than 0.1, for instance 0.01)

2) `ASD` metric 

3) display 2 different model uplift scores on one `qini plot`

**Comment by flashlight101** [comment]
#164
