### ISSUE TITLE
Issue with downloading sample dataset

### ISSUE THREAD

**Issue by eunkyung1127** [maks-sh/scikit-uplift#175]
Hello! I'm trying to run the tutorial file (RetailHero_EN.ipynb), and getting an error for fetch_x5() function.
I get '404 Not Found' error, and it seems the AWS bucket where the sample data files are located in is not available.
This is one of the file link that is not available: https://timds.s3.eu-central-1.amazonaws.com/uplift_train.csv.gz
Could you re-enable this AWS bucket? Thanks!

**Comment by maks-sh** [comment]
Hello!

Thank you for your feedback!🙌

Unfortunately, I need more time to fix the code in the package.
So now I will share the files as links on Google drive:
clients: https://drive.google.com/file/d/1USTn7dqw1cQR588h1GwMME8xtPRPHkqL/view?usp=sharing
train: https://drive.google.com/file/d/1RB76sMi1FY25mW4Iiqt9dQws6Ec7QVC2/view?usp=sharing
purchases: https://drive.google.com/file/d/1KO9t_PmhvQHP9HgKog3H6CDQu0JrEYky/view?usp=sharing

**Comment by eunkyung1127** [comment]
Thank you, Maksim!

**Comment by taozhuo2000** [comment]
It is very annoying if we can't run the tutorial file.

**Comment by shreejitpillai** [comment]
Thanks first of all to all those who contributed. Great work. Appreciate it! 

Purchases dataset is huge. Does anyone have a simpler dataset to work with?

**Comment by maks-sh** [comment]
@eunkyung1127 @taozhuo2000 👋

I apologize for waiting so long.
Now version 0.4.1 is available in pypi, which fixes this bug.
