### ISSUE TITLE
Models: y and treatment as Series 

### ISSUE THREAD

**Issue by ElisovaIra** [maks-sh/scikit-uplift#181]
## 🐛 Bug

Cannot pass `y` and `treatment` as Series to TwoModels when index does not match with `X` index 

<img width="536" alt="image" src="https://user-images.githubusercontent.com/16885007/175774076-6597d7b6-f87a-474a-974d-49a09b70d9ba.png">

## Expected behavior

Create checker 

## Environment

 - scikit-uplift version (e.g., 0.1.2): 0.4.1

**Comment by maks-sh** [comment]
Implemented in 0.5.0
