### ISSUE TITLE
Total in uplift_by_percentile might be confusing

### ISSUE THREAD

**Issue by baendigreydo** [maks-sh/scikit-uplift#84]
Hi all,
thanks for providing this package!

I'm getting my fingers dirty on the package for my thesis and came across the following:
In the calculation of ["uplift_by_percentile" ](https://github.com/maks-sh/scikit-uplift/blob/412b4904397628d1e1101b7c6c4a561cc2ef38f5/sklift/metrics/metrics.py#L543-L666) it is referring to the definition of ["weighted_average_uplift](https://github.com/maks-sh/scikit-uplift/blob/412b4904397628d1e1101b7c6c4a561cc2ef38f5/sklift/metrics/metrics.py#L486-L540).
Unfortunately, the results differ - see in the example:
![upbyperc](https://user-images.githubusercontent.com/71141543/109952281-f29ea800-7cde-11eb-9a5a-c8252e4a2666.JPG)
i calculated the uplift_by_percentile for the models and displayed the total column - same value for all models.
![waup](https://user-images.githubusercontent.com/71141543/109952280-f29ea800-7cde-11eb-95ba-48ca1b9cd18b.JPG)
when calculating the weighted_average_uplift with its dedicated function different values are shown...
![tz](https://user-images.githubusercontent.com/71141543/109952278-f2061180-7cde-11eb-9361-c9bacb97f147.JPG)
by setting total=False and calculating it manually, the result is 0.473009...
![manu](https://user-images.githubusercontent.com/71141543/109952275-f16d7b00-7cde-11eb-89cb-df6e80341ccb.JPG)
calculating it manually the result is again 0.473009... or 0.473010 due to rounding.

Maybe someone can shed some light on this issue. Thanks in advance.

**Comment by ElisovaIra** [comment]
Hi @baendigreydo,

Thank you for using our package, highlighting the problem and providing a nice description.

There is a mistake in the `uplift_by_percentile` docstring (sorry for that! 🤦🏻‍♀️)

in the `total` row `uplift` is calculated as:

`uplift_total` = `response_rate_trmnt_total ` -` response_rate_control_total`

This is why you get the same results in different models - total test response rates are the same.

**Comment by maks-sh** [comment]
Thank you so much!

Fixed in version 0.3.2.
