### ISSUE TITLE
Unwanted treatment variable in plot_uplift_preds( )

### ISSUE THREAD

**Issue by anwarbabukm** [maks-sh/scikit-uplift#86]
## 🐛 Bug
Error : 'treatment is not defined'

Causing the error 'treatment is not defined' while running the plot_uplift_preds( )
## To Rectify

- check_is_binary(treatment) seems unnecessary for this particular visualization function.

**Comment by maks-sh** [comment]
Hi!

Thanks for the issue. 

It is really a bug 🐛 .

**Comment by bwbelljr** [comment]
Created a pull request to remove the unnecessary line. This is also causing a problem for a tutorial I am working through.

**Comment by maks-sh** [comment]
Thank you so much!

Fixed in version 0.3.2.
