### ISSUE TITLE
DataFrame object has no attribute 'column' in fetch_x5 function call

### ISSUE THREAD

**Issue by Muhamob** [maks-sh/scikit-uplift#89]
## 🐛 Bug

There is a bag while attempting to fetch x5 dataset with fetch_x5() function. It failts to get attribute 'column' from dataframe

## To Reproduce

```python
from sklift import datasets
datasets.fetch_x5()
```

## Expected behavior

Dataset should be fetched with no errors

## Environment

 - scikit-uplift version (e.g., 0.1.2): 0.3.1
 - scikit-learn version (e.g., 0.22.2): 0.23.2
 - Python version (e.g., 3.7): 3.7.6
 - OS (e.g., Linux): Debian
 - Any other relevant information:

**Comment by maks-sh** [comment]
Hi!

Thanks for the feedback! 👍 

It is really a misprint in code: it should be `columns` attribute instead of `column`.

**Comment by maks-sh** [comment]
Thank you so much!

Fixed in version 0.3.2.
