### ISSUE TITLE
Checker: add checker that target is binary

### ISSUE THREAD

**Issue by ElisovaIra** [maks-sh/scikit-uplift#98]
## 💡 Feature request

`check_is_binary` checker function already exists. Please add it in the code for target checking.

## Motivation

Users try to fit datasets with a continuous target. There is no such option for now.

## Additional context

**Source:**

`check_is_binary` in `utils.py`. [Link here](https://github.com/maks-sh/scikit-uplift/blob/master/sklift/utils/utils.py)

**Where to add:**

- `models/models.py`  [Example usage](https://github.com/maks-sh/scikit-uplift/blob/e9de7abbb327fd461c1fe8bea5c4a1f25d0a823e/sklift/models/models.py#L96) 

- `metrics/metrics.py` 

- `viz/base.py`

**Comment by Ksyula** [comment]
take it

**Comment by Ksyula** [comment]
PR https://github.com/maks-sh/scikit-uplift/pull/120
