### ISSUE TITLE
Add Megafon dataset in sklift.datasets

### ISSUE THREAD

**Issue by maks-sh** [maks-sh/scikit-uplift#99]
## 💡 Feature request

Add new function `fetch_megafon` that loads and return train part of the Megafon dataset

## Motivation

Recently, one of the Russian telecom companies (Megafon) provide the [MegaFon Uplift Competition](https://ods.ai/tracks/df21-megafon/competitions/megafon-df21-comp)

The real data of Megafon company is sensitive data, and they are very responsible for the confidentiality of information. Therefore, they generated synthetic data, trying to bring them closer to the real case that they encountered.

We want it to be convenient for researchers to use our package so we try to collect datasets for uplift modeling in one place

If you have any problems getting access to the data write to us at team@uplift-modeling.com

**Comment by ezhdi** [comment]
take it
